export const Application_Constants = {
    foundation_11th_Title: '11th Foundation',
    foundation_11th_SubTitle:'For 10th Passed student',
    foundation_11th_Content: 'Batch running from 20th August',
    foundation_11th_Image:'/assets/images/classroom1.jpg',
    foundation_12th_Title: '12th Foundation',
    foundation_12th_SubTitle:'For 11th Passed student',
    foundation_12th_Content: 'Batch running from 20th August',
    foundation_12th_Image:'/assets/images/classroom2.jpg',
    neetTarget_Title: 'NEET Medical Target',
    neetTarget_SubTitle:'For medical aspirant',
    neetTarget_Content: 'Batch will announce shortly',
    neetTarget_Image:'/assets/images/doctor1.jpg',
    iitTarget_Title: 'IIT JEE Target',
    iitTarget_SubTitle:'For IIT JEE Engineering aspirant',
    iitTarget_Content: 'Batch will announce shortly',
    iitTarget_Image:'/assets/images/iittarget.jpg',
    tileButtonTitle: 'Enroll now',
    tileButtonLink: '/contact',
    tileButtonTitleEnquiry: 'Get enquery',
}